### ISSUE TITLE
DLL load failed while importing PyOptix: The specified module could not be found.

### ISSUE THREAD

**Issue by Skorkmaz88** [CompN3rd/ShapeFromCaustics#1]
Hi , 

First thanks for sharing this code.

I am trying to setup the codebase,  so far cmake steps worked and the python setup.py command with updated Optix 
folders are set. I was able to complete the build process without an error. Finally when I run the command

`python shape_from_caustics.py --help`

Output:

`Traceback (most recent call last):
  File "shape_from_caustics.py", line 9, in <module>
    from model.caustics import compute_recursive_refraction, compute_point_light_dirs, fused_silica, get_normal_from_height_field
  File "C:\Users\Besitzer\Documents\GitHub\ShapeFromCaustics\model\caustics.py", line 3, in <module>
    import PyOptix as popt
ImportError: DLL load failed while importing PyOptix: The specified module could not be found.`

Overall my setup is  : 

```
- Windows 10 64 bit
- Python 3.8 (Anaconda)
- Optix 6.5
- Cuda version 10.2
```

Let me know if more information would be needed.

**Comment by CompN3rd** [comment]
Hi, 

thank you for trying (and error checking) the code. 
I believe this might be due to the Extension not finding the OptiX .dll.
I checked and I have 'C:\ProgramData\NVIDIA Corporation\OptiX SDK 6.5.0\bin64' in my PATH variable. I forgot to add that to the readme.

Let me know if this resolves the error.

**Comment by Skorkmaz88** [comment]
Thanks, it did solve the problem

**Comment by Bardreamaster** [comment]
> Hi,
> 
> thank you for trying (and error checking) the code. I believe this might be due to the Extension not finding the OptiX .dll. I checked and I have 'C:\ProgramData\NVIDIA Corporation\OptiX SDK 6.5.0\bin64' in my PATH variable. I forgot to add that to the readme.
> 
> Let me know if this resolves the error.

I also meet the problem that ``` ImportError: DLL load failed while importing PyOptix: The specified module could not be found.```

And I have tried to add the `\bin64` path into system variables but it doesn't work.

My development env is the same as @Skorkmaz88 .
